#!/usr/bin/env python

import ROOT
from array import array
from math import *
import numpy as np 

t= ROOT.TGraphErrors()


dE = ROOT.TF1("dE","[0]*x+[1]",1319,1502);



lst =[5105, 5155, 5388, 5443, 5485, 5763, 5805]
y = np.array(lst)

lst = [1319.5, 1331.4, 1393, 1407.3, 1418, 1490.7, 1501.4]
x = np.array(lst);
k=0
for i,j in zip(x,y):
    t.SetPoint(k,i,j);
    k=k+1;


t.Fit("dE")

lst = [3.1, 3.1, 3.4, 2.9, 2.6, 3.1, 2.3]  
errx = np.array(lst);
 
k=0;
for e in errx:
     t.SetPointError(k, e, 0); 
     k=k+1;
       
c1 = ROOT.TCanvas("c1", "c1");

t.SetMarkerStyle(20);
t.SetMarkerSize(1);
#g.SetMarkerStyle(20);
#g.SetMarkerSize(1);
t.GetXaxis().SetRangeUser(1290, 1505);
t.GetYaxis().SetRangeUser(5105,5810);
t.SetTitle("Calibrazione");
t.GetYaxis().SetTitle("E [keV]")
t.GetXaxis().SetTitle("ch_{picco}")
t.SetLineColor(4)
t.SetMarkerColor(4)
#g.SetLineColor(4)
#g.SetMarkerColor(4)


t.Draw("AP");
#g.Draw("P");
dE.Draw("same");

input()
